### ISSUE TITLE
decommission unneeded VMs

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/web-archiving#13]
(ask @nullhandle before decommissioning any VMs ...)

* heritrix-dev?
* sfm-dev?
* was-downloader?
* webcapture-xx?

**Comment by lmcglohon** [comment]
I believe the webcapture-xx VMs are still needed because they are the heritrix machines.  
was-registrar VMs can probably be decommissioned, right @nullhandle ?
Not sure about the other ones.  @nullhandle can you please comment on all of these?

**Comment by nullhandle** [comment]
we may not be able to decommission as many as we originally thought. definitely keep sfm-dev, was-downloader, and webcapture-(all). heritrix-dev i believe was already decommissioned? was-registrar is still used to initiate registration and accessioning from the command-line for crawls and, apparently, it's the only way i currently know of to initiate seed accessioning (though there's probably a way to simply invoke the command on the command line).
