### ISSUE TITLE
update wasmetadata extractor docs

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/web-archiving#28]
- [x] devopsdocs:  explain that was-robot-suite rake task pulls a deployment artifact from jenkins
   - [x] WasMetadataExtractor ops concerns
   - [x] was_robot_suite ops concerns
- [x]  update jenkins description to reflect this
- [x]  put this explanation in README of 
  - [x] was_robot_suite (also mention openwayback inclusion in rake task)
  - [x] wasmdextractor docs.
  - [x] openwayback?

**Comment by ndushay** [comment]
additionally, from sul-dlss/WASMetadataExtractor#4:

must haves:
- [x] operations checklist written
- [x] mailing list (indicate in checklist and ops concerns?)

at least add TODOs for to prod checklist for
- [x] badges on README for release, and the below,
- [x] travis build that runs tests (if not deploying from jenkins, remove from jenkins)
- [x] coveralls for tests (see dlss-wowza for how to use coveralls w java)

see also #5

**Comment by ndushay** [comment]
once PRs are taken, all done!
