### ISSUE TITLE
review robot reliability proposals

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/web-archiving#30]
per meeting held Tues 1/17/2017

**Comment by ndushay** [comment]
In progress here:  https://github.com/sul-dlss/robot-master/wiki/Proposal(s)-for-Improving-Robot-Reliability

**Comment by drh-stanford** [comment]
need to order proposals by some scheme (i.e., short/long term, etc).

**Comment by drh-stanford** [comment]
Made major revision and retitled -- see https://github.com/sul-dlss/robot-master/wiki/Proposal:-Robot-Reliability

**Comment by drh-stanford** [comment]
just need to send this out for review now...
