### ISSUE TITLE
write ?consul page? about archiveit hierarchy of accounts -> collections -> crawls

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/web-archiving#38]
We will have a single downloader account per achive-it subscription;

each account has multiple collections

each collection has multiple crawls.

**Comment by cmharlow** [comment]
pass at documenting this and some on the WASAPI account data publication details (if only for later testing / confirming expectations of present data in test account) is here: https://consul.stanford.edu/pages/viewpage.action?pageId=157483820
