### ISSUE TITLE
is jobIdLowerBound a good param name?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/web-archiving#48]
see https://github.com/sul-dlss/wasapi-downloader/pull/72#pullrequestreview-40148407

**Comment by jmartin-sul** [comment]
@nullhandle?  we merged sul-dlss/wasapi-downloader#72 so we could unblock ourselves, but are happy to rename the parameter if desired (it's a string constant in one place, so that should be pretty quick/easy).

**Comment by ndushay** [comment]
@nullhandle is happy with the name.  Leave it.
